/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basketballscoreboard;

import javax.swing.JOptionPane;

/**
 *
 * @author Melva
 */
public class InitialConfig extends javax.swing.JFrame {

    /**
     * Creates new form InitialConfig
     */
    public InitialConfig() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        team1Name = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        qtrMinus = new javax.swing.JButton();
        qtrPlus = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        minutesLabel = new javax.swing.JLabel();
        qtrLength = new javax.swing.JLabel();
        team2Name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        timeoutMinus = new javax.swing.JButton();
        timeout = new javax.swing.JLabel();
        timeoutPlus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setFont(new java.awt.Font("HelveticaNeueLT Std Cn", 0, 14)); // NOI18N
        jLabel3.setText("Team 2 Name");

        team1Name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        team1Name.setForeground(new java.awt.Color(0, 102, 255));
        team1Name.setText("Guest");
        team1Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team1NameActionPerformed(evt);
            }
        });
        team1Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                team1NameKeyPressed(evt);
            }
        });

        startButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        startButton.setText("START GAME");
        startButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButtonMouseClicked(evt);
            }
        });
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("Wayne Dayata, 12-10-21");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Homizio Nova", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WMD Basketball Scoreboard");

        jLabel2.setFont(new java.awt.Font("HelveticaNeueLT Std Cn", 0, 14)); // NOI18N
        jLabel2.setText("Team 1 Name");

        qtrMinus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtrMinus.setText("-");
        qtrMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qtrMinusMouseClicked(evt);
            }
        });

        qtrPlus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtrPlus.setText("+");
        qtrPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qtrPlusMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("HelveticaNeueLT Std Cn", 0, 14)); // NOI18N
        jLabel5.setText("Quarter Length");

        minutesLabel.setFont(new java.awt.Font("HelveticaNeueLT Std Cn", 0, 14)); // NOI18N
        minutesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minutesLabel.setText("minutes");

        qtrLength.setFont(new java.awt.Font("HelveticaNeueLT Std Cn", 1, 18)); // NOI18N
        qtrLength.setForeground(new java.awt.Color(0, 102, 255));
        qtrLength.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtrLength.setText("10");

        team2Name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        team2Name.setForeground(new java.awt.Color(0, 102, 255));
        team2Name.setText("Home");
        team2Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                team2NameKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("HelveticaNeueLT Std Cn", 0, 14)); // NOI18N
        jLabel6.setText("Timeouts");

        timeoutMinus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        timeoutMinus.setText("-");
        timeoutMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeoutMinusMouseClicked(evt);
            }
        });

        timeout.setFont(new java.awt.Font("HelveticaNeueLT Std Cn", 1, 18)); // NOI18N
        timeout.setForeground(new java.awt.Color(0, 102, 255));
        timeout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeout.setText("7");
        timeout.setToolTipText("");

        timeoutPlus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        timeoutPlus.setText("+");
        timeoutPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeoutPlusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(team1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(team2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qtrMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(timeoutMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(qtrLength, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(minutesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(timeout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qtrPlus)
                                    .addComponent(timeoutPlus)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1)))
                        .addContainerGap(36, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(team1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(team2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(qtrMinus)
                    .addComponent(minutesLabel)
                    .addComponent(qtrPlus)
                    .addComponent(qtrLength, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(timeoutMinus)
                        .addComponent(timeoutPlus)
                        .addComponent(timeout, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void team1NameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_team1NameKeyPressed
      
    }//GEN-LAST:event_team1NameKeyPressed

    private void startButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseClicked
        String team1 = team1Name.getText();
        String team2 = team2Name.getText();
        int qtr = Integer.parseInt(qtrLength.getText());
        int to = Integer.parseInt(timeout.getText());
        
        if (team1.equals("") || team2.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the team names");
        } else {
            ScoreBoard sb = new ScoreBoard(team1,team2,qtr,to);
            sb.setVisible(true);
            sb.setDefaultCloseOperation(ScoreBoard.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_startButtonMouseClicked

    private void qtrMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qtrMinusMouseClicked
        int num = Integer.parseInt(qtrLength.getText()) - 1;
        qtrLength.setText(num + "");
        qtrPlus.setEnabled(true);
        if (num <= 1) {
            qtrMinus.setEnabled(false);
            minutesLabel.setText("minute");
            qtrLength.setText(1 + "");
        }
    }//GEN-LAST:event_qtrMinusMouseClicked

    private void qtrPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qtrPlusMouseClicked
        int num = Integer.parseInt(qtrLength.getText()) + 1;
        qtrLength.setText(num + "");
        qtrMinus.setEnabled(true);
        minutesLabel.setText("minutes");
        if (num >= 20) {
            qtrPlus.setEnabled(false);
            qtrLength.setText(20 + "");
        }

    }//GEN-LAST:event_qtrPlusMouseClicked

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startButtonActionPerformed

    private void team2NameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_team2NameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_team2NameKeyPressed

    private void team1NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team1NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_team1NameActionPerformed

    private void timeoutMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeoutMinusMouseClicked
        int num = Integer.parseInt(timeout.getText()) - 1;
        timeout.setText(num + "");
        timeoutPlus.setEnabled(true);
        if (num <= 0) {
            timeoutMinus.setEnabled(false);
            timeout.setText(0 + "");
        }
    }//GEN-LAST:event_timeoutMinusMouseClicked

    private void timeoutPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeoutPlusMouseClicked
        int num = Integer.parseInt(timeout.getText()) + 1;
        timeout.setText(num + "");
        timeoutMinus.setEnabled(true);
        if (num >= 10) {
            timeoutPlus.setEnabled(false);
            timeout.setText(10 + "");
        }
    }//GEN-LAST:event_timeoutPlusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitialConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitialConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitialConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitialConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InitialConfig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel minutesLabel;
    private javax.swing.JLabel qtrLength;
    private javax.swing.JButton qtrMinus;
    private javax.swing.JButton qtrPlus;
    private javax.swing.JButton startButton;
    private javax.swing.JTextField team1Name;
    private javax.swing.JTextField team2Name;
    private javax.swing.JLabel timeout;
    private javax.swing.JButton timeoutMinus;
    private javax.swing.JButton timeoutPlus;
    // End of variables declaration//GEN-END:variables
}
