/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basketballscoreboard;

import java.io.*;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Melva
 */
public class ScoreBoard extends javax.swing.JFrame {

    public int qtrLength;
    public boolean paused = true;
    public boolean started = false;

    /**
     * Creates new form NewJFrame
     */
    public ScoreBoard(String team1, String team2, int qtr, int to) {
        initComponents();
        T1name.setText(team1);
        T2name.setText(team2);
        gameClock.setText(qtr + ":00");
        qtrLength = qtr;
        T1to.setText(to + "");
        T2to.setText(to + "");

    }

    public ScoreBoard() {
        initComponents();
    }

    //Threads
    class T1 implements Runnable { //game clock

        private void sleep(long milis) {
            try {
                Thread.sleep(milis);
            } catch (InterruptedException e) {
                System.out.println(e);
            }
        }

        public synchronized void run() {
            while (paused == false && !gameClock.getText().equals("0.0")) {
                if (gameClock.getText().contains(":")) {
                    
                    String[] str = gameClock.getText().split(":");
                    int min = Integer.parseInt(str[0]);
                    int sec = Integer.parseInt(str[1]) - 1;
                    if (sec < 0) {
                        min -= 1;
                        sec = 59;
                    }
                    if (sec < 10) {
                        gameClock.setText(min + ":0" + sec);
                    } else {
                        gameClock.setText(min + ":" + sec);
                    }
                    if (min < 1) {
                        gameClock.setText("59.9");
                        continue;
                    }
                    sleep(1000);
                    
                } else {
                    
                    String[] str = gameClock.getText().split("\\.");
                    int sec = Integer.parseInt(str[0]);
                    int ms = Integer.parseInt(str[1]) - 1;
                    if (ms < 0) {
                        sec -= 1;
                        ms = 9;
                    }
                    if (sec < 0) {
                        gameClock.setText("0.0");
                        gameStart.setEnabled(false);
                    } else {
                        gameClock.setText(sec + "." + ms);
                    }
                    sleep(100);
                    
                }
            }
            if (gameClock.getText().equals("0.0")){
                gameClock.setForeground(Color.red);
            }
        }
    }

    //Threads
    class T2 implements Runnable { //shot clock

        private void sleep(long milis) {
            try {
                Thread.sleep(milis);
            } catch (InterruptedException e) {
                System.out.println(e);
            }
        }

        public synchronized void run() {

            while (paused == false && !shotClock.getText().equals("0.0") && !shotClock.getText().equals("")) {
                if (!shotClock.getText().contains(".")) {
                    
                    int sec = Integer.parseInt(shotClock.getText()) - 1;
                    if (sec < 5) {
                        shotClock.setText("4.9");
                        continue;
                    } else {
                        shotClock.setText(sec + "");
                    }
                    sleep(1000);
                    
                } else {
                    
                    String[] str = shotClock.getText().split("\\.");
                    int sec = Integer.parseInt(str[0]);
                    int ms = Integer.parseInt(str[1]) - 1;
                    if (ms < 0) {
                        sec -= 1;
                        ms = 9;
                    }
                    if (sec < 0) {
                        shotClock.setText("0.0");
                    } else {
                        shotClock.setText(sec + "." + ms);
                    }
                    sleep(100);
                    
                }
            }
            if(shotClock.getText().equals("0.0")){
                shotClock.setForeground(Color.red);
            }
        }
    }

    T1 t1 = new T1();
    Thread th1 = new Thread(t1);

    T2 t2 = new T2();
    Thread th2 = new Thread(t2);

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonsPanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        gameStart = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        gameStop = new javax.swing.JButton();
        gameReset = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        shotReset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        Team2Panel = new javax.swing.JPanel();
        T2name = new javax.swing.JLabel();
        T2score = new javax.swing.JLabel();
        T2fls = new javax.swing.JLabel();
        T2to = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Team1Panel = new javax.swing.JPanel();
        T1name = new javax.swing.JLabel();
        T1score = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        T1to = new javax.swing.JLabel();
        T1fls = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TimersPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        gameClock = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        shotClock = new javax.swing.JLabel();
        quarter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonsPanel.setBackground(new java.awt.Color(204, 204, 255));

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("+2");
        jButton3.setToolTipText("");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 204, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("+1");
        jButton4.setToolTipText("");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 204, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("+3");
        jButton5.setToolTipText("");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(153, 204, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("-1");
        jButton6.setToolTipText("");
        jButton6.setEnabled(false);
        jButton6.setPreferredSize(new java.awt.Dimension(50, 20));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(153, 204, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("TIMEOUT");
        jButton7.setToolTipText("");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(153, 204, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("FOUL");
        jButton8.setToolTipText("");
        jButton8.setPreferredSize(new java.awt.Dimension(50, 20));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("SCORE");

        gameStart.setBackground(new java.awt.Color(255, 255, 255));
        gameStart.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        gameStart.setText("START");
        gameStart.setToolTipText("");
        gameStart.setMargin(new java.awt.Insets(2, 5, 2, 5));
        gameStart.setPreferredSize(new java.awt.Dimension(50, 20));
        gameStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameStartMouseClicked(evt);
            }
        });
        gameStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameStartActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("GAME");

        gameStop.setBackground(new java.awt.Color(255, 255, 255));
        gameStop.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        gameStop.setText("STOP");
        gameStop.setToolTipText("");
        gameStop.setEnabled(false);
        gameStop.setMargin(new java.awt.Insets(2, 5, 2, 5));
        gameStop.setPreferredSize(new java.awt.Dimension(50, 20));
        gameStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameStopMouseClicked(evt);
            }
        });
        gameStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameStopActionPerformed(evt);
            }
        });

        gameReset.setBackground(new java.awt.Color(255, 255, 255));
        gameReset.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        gameReset.setToolTipText("");
        gameReset.setLabel("RESET");
        gameReset.setMargin(new java.awt.Insets(2, 5, 2, 5));
        gameReset.setPreferredSize(new java.awt.Dimension(50, 20));
        gameReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameResetMouseClicked(evt);
            }
        });
        gameReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameResetActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("SHOT");

        shotReset.setBackground(new java.awt.Color(255, 255, 255));
        shotReset.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        shotReset.setToolTipText("");
        shotReset.setLabel("RESET");
        shotReset.setPreferredSize(new java.awt.Dimension(50, 20));
        shotReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shotResetMouseClicked(evt);
            }
        });
        shotReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shotResetActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("QUARTER");

        jButton21.setBackground(new java.awt.Color(255, 255, 255));
        jButton21.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton21.setText("+");
        jButton21.setToolTipText("");
        jButton21.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jButton21.setPreferredSize(new java.awt.Dimension(50, 20));
        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton21MouseClicked(evt);
            }
        });
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(255, 255, 255));
        jButton22.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton22.setText("-");
        jButton22.setToolTipText("");
        jButton22.setEnabled(false);
        jButton22.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jButton22.setPreferredSize(new java.awt.Dimension(50, 20));
        jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton22MouseClicked(evt);
            }
        });
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 204, 204));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton11.setText("-1");
        jButton11.setToolTipText("");
        jButton11.setEnabled(false);
        jButton11.setPreferredSize(new java.awt.Dimension(50, 20));
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("SCORE");

        jButton12.setBackground(new java.awt.Color(255, 204, 204));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton12.setText("+1");
        jButton12.setToolTipText("");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(255, 204, 204));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton13.setText("+2");
        jButton13.setToolTipText("");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(255, 204, 204));
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton14.setText("+3");
        jButton14.setToolTipText("");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 204, 204));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setText("TIMEOUT");
        jButton10.setToolTipText("");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 204, 204));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setText("FOUL");
        jButton9.setToolTipText("");
        jButton9.setPreferredSize(new java.awt.Dimension(50, 20));
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonsPanelLayout = new javax.swing.GroupLayout(ButtonsPanel);
        ButtonsPanel.setLayout(ButtonsPanelLayout);
        ButtonsPanelLayout.setHorizontalGroup(
            ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsPanelLayout.createSequentialGroup()
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ButtonsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5))
                    .addGroup(ButtonsPanelLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gameStart, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(shotReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ButtonsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(8, 8, 8)
                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ButtonsPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(gameStop, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gameReset, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ButtonsPanelLayout.createSequentialGroup()
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton14))
                    .addGroup(ButtonsPanelLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel2)))
                .addGap(29, 29, 29)
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        ButtonsPanelLayout.setVerticalGroup(
            ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ButtonsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(9, 9, 9)
                        .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(gameStart, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gameStop, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gameReset, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ButtonsPanelLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shotReset, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ButtonsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)
                        .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ButtonsPanelLayout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Team2Panel.setBackground(new java.awt.Color(153, 51, 0));
        Team2Panel.setForeground(new java.awt.Color(255, 255, 255));

        T2name.setFont(new java.awt.Font("Diavlo Bold", 0, 30)); // NOI18N
        T2name.setForeground(new java.awt.Color(255, 255, 255));
        T2name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T2name.setText("HOME");

        T2score.setBackground(new java.awt.Color(0, 0, 0));
        T2score.setFont(new java.awt.Font("Digital-7", 1, 240)); // NOI18N
        T2score.setForeground(new java.awt.Color(51, 255, 0));
        T2score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T2score.setText("0");
        T2score.setToolTipText("");

        T2fls.setBackground(new java.awt.Color(0, 0, 0));
        T2fls.setFont(new java.awt.Font("Digital Dismay", 1, 60)); // NOI18N
        T2fls.setForeground(new java.awt.Color(153, 255, 255));
        T2fls.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T2fls.setText("0");
        T2fls.setToolTipText("");

        T2to.setBackground(new java.awt.Color(0, 0, 0));
        T2to.setFont(new java.awt.Font("Digital Dismay", 1, 60)); // NOI18N
        T2to.setForeground(new java.awt.Color(153, 255, 255));
        T2to.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T2to.setText("7");
        T2to.setToolTipText("");

        jLabel19.setFont(new java.awt.Font("Nunito ExtraBold", 1, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("FLS");

        jLabel17.setFont(new java.awt.Font("Nunito ExtraBold", 1, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("TO");

        javax.swing.GroupLayout Team2PanelLayout = new javax.swing.GroupLayout(Team2Panel);
        Team2Panel.setLayout(Team2PanelLayout);
        Team2PanelLayout.setHorizontalGroup(
            Team2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Team2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T2name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T2score, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Team2PanelLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T2to, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(T2fls, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        Team2PanelLayout.setVerticalGroup(
            Team2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team2PanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(T2name, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T2score, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Team2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T2to)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T2fls))
                .addGap(39, 39, 39))
        );

        Team1Panel.setBackground(new java.awt.Color(0, 0, 153));
        Team1Panel.setForeground(new java.awt.Color(255, 255, 255));

        T1name.setFont(new java.awt.Font("Diavlo Bold", 0, 30)); // NOI18N
        T1name.setForeground(new java.awt.Color(255, 255, 255));
        T1name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T1name.setText("GUEST");

        T1score.setBackground(new java.awt.Color(0, 0, 0));
        T1score.setFont(new java.awt.Font("Digital-7", 1, 240)); // NOI18N
        T1score.setForeground(new java.awt.Color(51, 255, 0));
        T1score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T1score.setText("0");
        T1score.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Nunito ExtraBold", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("TO");

        T1to.setBackground(new java.awt.Color(0, 0, 0));
        T1to.setFont(new java.awt.Font("Digital Dismay", 1, 60)); // NOI18N
        T1to.setForeground(new java.awt.Color(153, 255, 255));
        T1to.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T1to.setText("7");
        T1to.setToolTipText("");

        T1fls.setBackground(new java.awt.Color(0, 0, 0));
        T1fls.setFont(new java.awt.Font("Digital Dismay", 1, 60)); // NOI18N
        T1fls.setForeground(new java.awt.Color(153, 255, 255));
        T1fls.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T1fls.setText("0");
        T1fls.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Nunito ExtraBold", 1, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("FLS");

        javax.swing.GroupLayout Team1PanelLayout = new javax.swing.GroupLayout(Team1Panel);
        Team1Panel.setLayout(Team1PanelLayout);
        Team1PanelLayout.setHorizontalGroup(
            Team1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team1PanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T1to, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(T1fls, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(Team1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Team1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T1score, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(T1name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Team1PanelLayout.setVerticalGroup(
            Team1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team1PanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(T1name, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T1score, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(Team1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T1to)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T1fls))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        TimersPanel.setBackground(new java.awt.Color(0, 0, 0));
        TimersPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Diavlo Bold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TIME");

        gameClock.setBackground(new java.awt.Color(0, 0, 0));
        gameClock.setFont(new java.awt.Font("Digital-7", 1, 110)); // NOI18N
        gameClock.setForeground(new java.awt.Color(255, 255, 0));
        gameClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameClock.setText("10:00");
        gameClock.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Nunito ExtraBold", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("QTR");

        shotClock.setBackground(new java.awt.Color(0, 0, 0));
        shotClock.setFont(new java.awt.Font("Digital-7", 1, 110)); // NOI18N
        shotClock.setForeground(new java.awt.Color(255, 255, 0));
        shotClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shotClock.setText("24");
        shotClock.setToolTipText("");

        quarter.setBackground(new java.awt.Color(0, 0, 0));
        quarter.setFont(new java.awt.Font("Digital-7", 1, 110)); // NOI18N
        quarter.setForeground(new java.awt.Color(255, 255, 0));
        quarter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quarter.setText("1");
        quarter.setToolTipText("");

        javax.swing.GroupLayout TimersPanelLayout = new javax.swing.GroupLayout(TimersPanel);
        TimersPanel.setLayout(TimersPanelLayout);
        TimersPanelLayout.setHorizontalGroup(
            TimersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimersPanelLayout.createSequentialGroup()
                .addGroup(TimersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TimersPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(TimersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TimersPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(quarter, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(gameClock, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TimersPanelLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TimersPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(shotClock, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        TimersPanelLayout.setVerticalGroup(
            TimersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimersPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameClock, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(shotClock, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(TimersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(quarter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Team1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TimersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Team2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TimersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Team1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Team2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void gameStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameStartActionPerformed

    private void gameStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameStopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameStopActionPerformed

    private void gameResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameResetActionPerformed

    private void shotResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shotResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shotResetActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        int num = Integer.parseInt(T1score.getText()) - 1;
        T1score.setText(num + "");
        if (num <= 0) {
            jButton6.setEnabled(false);
            T1score.setText(0 + "");
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        int num = Integer.parseInt(T2score.getText()) - 1;
        T2score.setText(num + "");
        if (num <= 0) {
            jButton11.setEnabled(false);
            T2score.setText(0 + "");
        }
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        int num = Integer.parseInt(T1score.getText()) + 1;
        T1score.setText(num + "");
        jButton6.setEnabled(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        int num = Integer.parseInt(T1score.getText()) + 2;
        T1score.setText(num + "");
        jButton6.setEnabled(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        int num = Integer.parseInt(T1score.getText()) + 3;
        T1score.setText(num + "");
        jButton6.setEnabled(true);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        int num = Integer.parseInt(T2score.getText()) + 1;
        T2score.setText(num + "");
        jButton11.setEnabled(true);
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        int num = Integer.parseInt(T2score.getText()) + 2;
        T2score.setText(num + "");
        jButton11.setEnabled(true);
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        int num = Integer.parseInt(T2score.getText()) + 3;
        T2score.setText(num + "");
        jButton11.setEnabled(true);
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        int num = Integer.parseInt(T1to.getText()) - 1;
        T1to.setText(num + "");
        if (num <= 0) {
            jButton7.setEnabled(false);
            T1to.setText(0 + "");
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        int num = Integer.parseInt(T2to.getText()) - 1;
        T2to.setText(num + "");
        if (num <= 0) {
            jButton10.setEnabled(false);
            T2to.setText(0 + "");
        }
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        int num = Integer.parseInt(T1fls.getText()) + 1;
        T1fls.setText(num + "");
        if (num >= 9) {
            jButton8.setEnabled(false);
            T1fls.setText(9 + "");
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        int num = Integer.parseInt(T2fls.getText()) + 1;
        T2fls.setText(num + "");
        if (num >= 9) {
            jButton9.setEnabled(false);
            T2fls.setText(9 + "");
        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseClicked
        int num = Integer.parseInt(quarter.getText()) - 1;
        jButton21.setEnabled(true);
        quarter.setText(num + "");
        if (num <= 1) {
            jButton22.setEnabled(false);
            quarter.setText(1 + "");
        }
    }//GEN-LAST:event_jButton22MouseClicked

    private void jButton21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseClicked
        int num = Integer.parseInt(quarter.getText()) + 1;
        jButton22.setEnabled(true);
        quarter.setText(num + "");
        if (num >= 9) {
            jButton21.setEnabled(false);
            quarter.setText(9 + "");
        }
    }//GEN-LAST:event_jButton21MouseClicked

    private void gameStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameStartMouseClicked
        if (gameStart.isEnabled()) {
            gameStart.setEnabled(false);
            gameReset.setEnabled(false);
            gameStop.setEnabled(true);
            paused = false;
            T1 t1 = new T1();
            Thread th1 = new Thread(t1);
            th1.start();
            T2 t2 = new T2();
            Thread th2 = new Thread(t2);
            th2.start();
        }

    }//GEN-LAST:event_gameStartMouseClicked

    private void gameStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameStopMouseClicked
        if (gameStop.isEnabled()) {
            gameStart.setEnabled(true);
            gameReset.setEnabled(true);
            gameStop.setEnabled(false);
            paused = true;
        }
    }//GEN-LAST:event_gameStopMouseClicked

    private void shotResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shotResetMouseClicked
        if (gameClock.getText().contains(".")){
            String[] str = gameClock.getText().split("\\.");
            if(Integer.parseInt(str[0])<24){
                shotClock.setText(""); //disable shot clock if game clock below 24s
            } else {
                shotClock.setText("24");
            }
        } else {
            shotClock.setText("24");
        }
        shotClock.setForeground(Color.yellow);
    }//GEN-LAST:event_shotResetMouseClicked

    private void gameResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameResetMouseClicked
        if (gameReset.isEnabled()) {
            gameClock.setText(qtrLength + ":00");
            shotClock.setText("24");
            gameClock.setForeground(Color.yellow);
            shotClock.setForeground(Color.yellow);
            gameReset.setEnabled(false);
        }
    }//GEN-LAST:event_gameResetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreBoard().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JLabel T1fls;
    private javax.swing.JLabel T1name;
    private javax.swing.JLabel T1score;
    private javax.swing.JLabel T1to;
    private javax.swing.JLabel T2fls;
    private javax.swing.JLabel T2name;
    private javax.swing.JLabel T2score;
    private javax.swing.JLabel T2to;
    private javax.swing.JPanel Team1Panel;
    private javax.swing.JPanel Team2Panel;
    private javax.swing.JPanel TimersPanel;
    private javax.swing.JLabel gameClock;
    private javax.swing.JButton gameReset;
    private javax.swing.JButton gameStart;
    private javax.swing.JButton gameStop;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel quarter;
    private javax.swing.JLabel shotClock;
    private javax.swing.JButton shotReset;
    // End of variables declaration//GEN-END:variables
}
