/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Melva
 */
import java.io.*;
import javax.swing.table.DefaultTableModel;

public class IS_AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form IS_AdminPanel
     */
    public IS_AdminPanel() {
        initComponents();
        refresh();
    }

    FileCRUD f = new FileCRUD();

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InventoryStatus = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        resetButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        editItemPanel = new javax.swing.JPanel();
        itemIdField = new javax.swing.JTextField();
        itemBrandField = new javax.swing.JTextField();
        itemNameField = new javax.swing.JTextField();
        categoryField = new javax.swing.JComboBox<>();
        qtyRemMinus = new javax.swing.JButton();
        qtyRemPlus = new javax.swing.JButton();
        qtyMaintainMinus = new javax.swing.JButton();
        qtyMaintainPlus = new javax.swing.JButton();
        qtyRemField = new javax.swing.JTextField();
        qtyMaintainField = new javax.swing.JTextField();
        storeLocField = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        clickAnItemLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        storeLocField1 = new javax.swing.JTextField();
        categoryField1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        qtyRemField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        qtyRemMinus1 = new javax.swing.JButton();
        qtyRemPlus1 = new javax.swing.JButton();
        confirm1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        qtyMaintainMinus1 = new javax.swing.JButton();
        qtyMaintainField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        qtyMaintainPlus1 = new javax.swing.JButton();
        itemNameField1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        itemBrandField1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        displayCriticalButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        InventoryStatus.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel1.setText("Inventory Status");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Item", "Brand", "Category", "Qty Remaining", "Qty to Maintain", "Store Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(50);
        }

        searchButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchButton.setText("Go");
        searchButton.setEnabled(false);
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Search item name/brand/category:");

        searchBar.setBackground(new java.awt.Color(240, 240, 240));
        searchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBarKeyReleased(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetButtonMouseClicked(evt);
            }
        });
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 255, 153));

        editItemPanel.setBackground(new java.awt.Color(51, 255, 153));

        itemIdField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        itemIdField.setEnabled(false);

        itemBrandField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        itemNameField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        itemNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameFieldActionPerformed(evt);
            }
        });

        categoryField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food (Perishable)", "Food (Non-perishable)", "Pantry", "Cosmetics", "Cleaning Products", "Miscellaneous", " " }));

        qtyRemMinus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtyRemMinus.setText("-");
        qtyRemMinus.setEnabled(false);
        qtyRemMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qtyRemMinusMouseClicked(evt);
            }
        });

        qtyRemPlus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtyRemPlus.setText("+");
        qtyRemPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qtyRemPlusMouseClicked(evt);
            }
        });

        qtyMaintainMinus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtyMaintainMinus.setText("-");
        qtyMaintainMinus.setEnabled(false);
        qtyMaintainMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qtyMaintainMinusMouseClicked(evt);
            }
        });
        qtyMaintainMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyMaintainMinusActionPerformed(evt);
            }
        });

        qtyMaintainPlus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtyMaintainPlus.setText("+");
        qtyMaintainPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qtyMaintainPlusMouseClicked(evt);
            }
        });

        qtyRemField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        qtyRemField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtyRemField.setText("0");
        qtyRemField.setToolTipText("");
        qtyRemField.setEnabled(false);
        qtyRemField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyRemFieldActionPerformed(evt);
            }
        });

        qtyMaintainField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        qtyMaintainField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtyMaintainField.setText("0");
        qtyMaintainField.setToolTipText("");
        qtyMaintainField.setEnabled(false);
        qtyMaintainField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyMaintainFieldActionPerformed(evt);
            }
        });

        storeLocField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        confirm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirm.setText("Confirm");
        confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("HelveticaNeueLT Std Cn", 0, 14)); // NOI18N
        jLabel8.setText("Name:");

        jLabel11.setFont(new java.awt.Font("HelveticaNeueLT Std Cn", 0, 14)); // NOI18N
        jLabel11.setText("Quantity Remaining:");

        jLabel10.setFont(new java.awt.Font("HelveticaNeueLT Std Cn", 0, 14)); // NOI18N
        jLabel10.setText("Brand:");

        jLabel13.setFont(new java.awt.Font("HelveticaNeueLT Std Cn", 0, 14)); // NOI18N
        jLabel13.setText("Quantity to Maintain:");

        jLabel14.setFont(new java.awt.Font("HelveticaNeueLT Std Cn", 0, 14)); // NOI18N
        jLabel14.setText("Category: ");

        jLabel15.setFont(new java.awt.Font("HelveticaNeueLT Std Cn", 0, 14)); // NOI18N
        jLabel15.setText("Store Location:");

        jLabel12.setFont(new java.awt.Font("HelveticaNeueLT Std Cn", 0, 14)); // NOI18N
        jLabel12.setText("ID:");

        jButton3.setBackground(new java.awt.Color(255, 255, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 51, 0));
        jButton3.setText("Delete");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editItemPanelLayout = new javax.swing.GroupLayout(editItemPanel);
        editItemPanel.setLayout(editItemPanelLayout);
        editItemPanelLayout.setHorizontalGroup(
            editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editItemPanelLayout.createSequentialGroup()
                .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editItemPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editItemPanelLayout.createSequentialGroup()
                                .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(editItemPanelLayout.createSequentialGroup()
                                        .addComponent(qtyMaintainMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(qtyMaintainField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(qtyMaintainPlus))
                                    .addGroup(editItemPanelLayout.createSequentialGroup()
                                        .addComponent(qtyRemMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(qtyRemField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(qtyRemPlus))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editItemPanelLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(categoryField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(53, 53, 53))
                            .addGroup(editItemPanelLayout.createSequentialGroup()
                                .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(28, 28, 28)
                                .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(itemNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(itemIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(itemBrandField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(editItemPanelLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(storeLocField))))
                    .addGroup(editItemPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editItemPanelLayout.setVerticalGroup(
            editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editItemPanelLayout.createSequentialGroup()
                .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editItemPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(editItemPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(itemIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemBrandField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qtyRemField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtyRemMinus)
                            .addComponent(qtyRemPlus)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(qtyMaintainField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(qtyMaintainPlus))
                            .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(qtyMaintainMinus)
                                .addComponent(jLabel13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(editItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(storeLocField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(0, 60, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );

        clickAnItemLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clickAnItemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clickAnItemLabel.setText("<html> Click an item on the <br> table to modify contents. <br><br>Click \"Add New Item\" above <br> to insert a new item. </html>");
        clickAnItemLabel.setToolTipText("");
        clickAnItemLabel.setFocusable(false);
        clickAnItemLabel.setPreferredSize(new java.awt.Dimension(100, 110));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editItemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(clickAnItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editItemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(clickAnItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(61, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Edit Item", jPanel1);

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));

        storeLocField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        categoryField1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food (Perishable)", "Food (Non-perishable)", "Pantry", "Cosmetics", "Cleaning Products", "Miscellaneous", " " }));

        jLabel16.setFont(new java.awt.Font("HelveticaNeueLT Std Cn", 0, 14)); // NOI18N
        jLabel16.setText("Quantity Remaining:");

        qtyRemField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        qtyRemField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtyRemField1.setText("0");
        qtyRemField1.setToolTipText("");
        qtyRemField1.setEnabled(false);
        qtyRemField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyRemField1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel17.setText("Create New Item");

        qtyRemMinus1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtyRemMinus1.setText("-");
        qtyRemMinus1.setEnabled(false);
        qtyRemMinus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qtyRemMinus1MouseClicked(evt);
            }
        });

        qtyRemPlus1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtyRemPlus1.setText("+");
        qtyRemPlus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qtyRemPlus1MouseClicked(evt);
            }
        });

        confirm1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirm1.setText("Confirm");
        confirm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirm1MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("HelveticaNeueLT Std Cn", 0, 14)); // NOI18N
        jLabel18.setText("Quantity to Maintain:");

        qtyMaintainMinus1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtyMaintainMinus1.setText("-");
        qtyMaintainMinus1.setEnabled(false);
        qtyMaintainMinus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qtyMaintainMinus1MouseClicked(evt);
            }
        });

        qtyMaintainField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        qtyMaintainField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtyMaintainField1.setText("0");
        qtyMaintainField1.setToolTipText("");
        qtyMaintainField1.setEnabled(false);
        qtyMaintainField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyMaintainField1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("HelveticaNeueLT Std Cn", 0, 14)); // NOI18N
        jLabel9.setText("Name:");

        qtyMaintainPlus1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtyMaintainPlus1.setText("+");
        qtyMaintainPlus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qtyMaintainPlus1MouseClicked(evt);
            }
        });

        itemNameField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        itemNameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameField1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("HelveticaNeueLT Std Cn", 0, 14)); // NOI18N
        jLabel19.setText("Category: ");

        itemBrandField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel20.setFont(new java.awt.Font("HelveticaNeueLT Std Cn", 0, 14)); // NOI18N
        jLabel20.setText("Store Location:");

        jLabel21.setFont(new java.awt.Font("HelveticaNeueLT Std Cn", 0, 14)); // NOI18N
        jLabel21.setText("Brand:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(qtyMaintainMinus1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(qtyMaintainField1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(qtyMaintainPlus1))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(qtyRemMinus1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(qtyRemField1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(qtyRemPlus1))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(storeLocField1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel9)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(categoryField1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(53, 53, 53))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(itemBrandField1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(itemNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirm1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel17)
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemBrandField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(categoryField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyRemField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyRemMinus1)
                    .addComponent(qtyRemPlus1)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(qtyMaintainField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(qtyMaintainPlus1))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(qtyMaintainMinus1)
                        .addComponent(jLabel18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(storeLocField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(confirm1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Add New Item", jPanel5);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("Wayne Dayata, 10-31-21");

        jLabel5.setForeground(new java.awt.Color(255, 255, 102));
        jLabel5.setText("May reklamo ka? Itawag sa LTFRB (420-DURC)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        displayCriticalButton.setBackground(new java.awt.Color(255, 153, 153));
        displayCriticalButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        displayCriticalButton.setLabel("Display critical stocks");
        displayCriticalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayCriticalButtonMouseClicked(evt);
            }
        });
        displayCriticalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayCriticalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InventoryStatusLayout = new javax.swing.GroupLayout(InventoryStatus);
        InventoryStatus.setLayout(InventoryStatusLayout);
        InventoryStatusLayout.setHorizontalGroup(
            InventoryStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(InventoryStatusLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(InventoryStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InventoryStatusLayout.createSequentialGroup()
                        .addGroup(InventoryStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InventoryStatusLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resetButton)
                                .addGap(18, 18, 18)
                                .addComponent(displayCriticalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(InventoryStatusLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)))
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        InventoryStatusLayout.setVerticalGroup(
            InventoryStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventoryStatusLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(InventoryStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InventoryStatusLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(InventoryStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayCriticalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InventoryStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InventoryStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void qtyMaintainFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyMaintainFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyMaintainFieldActionPerformed

    private void qtyRemFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyRemFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyRemFieldActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void itemNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameFieldActionPerformed

    private void itemNameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameField1ActionPerformed

    private void qtyMaintainField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyMaintainField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyMaintainField1ActionPerformed

    private void qtyRemField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyRemField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyRemField1ActionPerformed

    private void displayCriticalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayCriticalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayCriticalButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        editItemPanel.setVisible(false);
        clickAnItemLabel.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        /*Prompt user to confirm item deletion, then remove from database and refresh table*/
        int del = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the selected item record ?");
        if (del == 0) {
            int id = Integer.parseInt(itemIdField.getText());
            f.deleteItem(id);
            JOptionPane.showMessageDialog(null, "Item record deleted!");
            editItemPanel.setVisible(false); //hides the edit item components
            clickAnItemLabel.setVisible(true);
            refresh();
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();

        /*setting values to the update item tab*/
        itemIdField.setText(model.getValueAt(row, 0).toString());
        itemBrandField.setText(model.getValueAt(row, 2).toString());
        itemNameField.setText(model.getValueAt(row, 1).toString());
        categoryField.setSelectedItem(model.getValueAt(row, 3).toString());
        qtyRemField.setText(model.getValueAt(row, 4).toString());
        qtyMaintainField.setText(model.getValueAt(row, 5).toString());
        storeLocField.setText(model.getValueAt(row, 6).toString());

        if (Integer.parseInt(qtyRemField.getText()) > 0) {
            qtyRemMinus.setEnabled(true);
        }
        if (Integer.parseInt(qtyMaintainField.getText()) > 0) {
            qtyMaintainMinus.setEnabled(true);
        }

        editItemPanel.setVisible(true);
        clickAnItemLabel.setVisible(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void qtyRemMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qtyRemMinusMouseClicked
        int num = Integer.parseInt(qtyRemField.getText()) - 1;
        qtyRemField.setText(num + "");
        if (num == 0) {
            qtyRemMinus.setEnabled(false);
        }
    }//GEN-LAST:event_qtyRemMinusMouseClicked

    private void qtyRemPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qtyRemPlusMouseClicked
        int num = Integer.parseInt(qtyRemField.getText()) + 1;
        qtyRemField.setText(num + "");
        qtyRemMinus.setEnabled(true);
    }//GEN-LAST:event_qtyRemPlusMouseClicked

    private void qtyMaintainMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyMaintainMinusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyMaintainMinusActionPerformed

    private void qtyMaintainMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qtyMaintainMinusMouseClicked
        int num = Integer.parseInt(qtyMaintainField.getText()) - 1;
        qtyMaintainField.setText(num + "");
        if (num == 0) {
            qtyMaintainMinus.setEnabled(false);
        }
    }//GEN-LAST:event_qtyMaintainMinusMouseClicked

    private void qtyMaintainPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qtyMaintainPlusMouseClicked
        int num = Integer.parseInt(qtyMaintainField.getText()) + 1;
        qtyMaintainField.setText(num + "");
        qtyMaintainMinus.setEnabled(true);
    }//GEN-LAST:event_qtyMaintainPlusMouseClicked

    private void searchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarKeyReleased
        String keyword = searchBar.getText();
        if (!"".equals(keyword)) {
            searchButton.setEnabled(true);
        } else {
            searchButton.setEnabled(false);
        }
    }//GEN-LAST:event_searchBarKeyReleased

    private void resetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButtonMouseClicked
        refresh();
    }//GEN-LAST:event_resetButtonMouseClicked

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        String keyword = searchBar.getText();
        if (!"".equals(keyword)) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            String[][] list = f.searchItems(keyword);
            displayTable(list);            
        } else {
            JOptionPane.showMessageDialog(null, "Please enter keywords to search");
        }
    }//GEN-LAST:event_searchButtonMouseClicked

    private void confirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmMouseClicked
        /*update item*/
        int id = Integer.parseInt(itemIdField.getText());
        String[] item = new String[6];
        item[0] = itemNameField.getText();
        item[1] = itemBrandField.getText();
        item[2] = categoryField.getSelectedItem().toString();
        item[3] = qtyRemField.getText();
        item[4] = qtyMaintainField.getText();
        item[5] = storeLocField.getText();


        if (!"".equals(item[0]) && !"".equals(item[1]) && !"".equals(item[2])) {
            f.updateItem(id,item);
            JOptionPane.showMessageDialog(null, "Item record successfully updated!");
            refresh();
        } else {
            JOptionPane.showMessageDialog(null, "Please fill in all information");
        }
    }//GEN-LAST:event_confirmMouseClicked

    private void qtyRemMinus1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qtyRemMinus1MouseClicked
        int num = Integer.parseInt(qtyRemField1.getText()) - 1;
        qtyRemField1.setText(num + "");
        if (num == 0) {
            qtyRemMinus1.setEnabled(false);
        }
    }//GEN-LAST:event_qtyRemMinus1MouseClicked

    private void qtyMaintainMinus1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qtyMaintainMinus1MouseClicked
        int num = Integer.parseInt(qtyMaintainField1.getText()) - 1;
        qtyMaintainField1.setText(num + "");
        if (num == 0) {
            qtyMaintainMinus1.setEnabled(false);
        }
    }//GEN-LAST:event_qtyMaintainMinus1MouseClicked

    private void qtyRemPlus1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qtyRemPlus1MouseClicked
        int num = Integer.parseInt(qtyRemField1.getText()) + 1;
        qtyRemField1.setText(num + "");
        qtyRemMinus1.setEnabled(true);
    }//GEN-LAST:event_qtyRemPlus1MouseClicked

    private void qtyMaintainPlus1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qtyMaintainPlus1MouseClicked
        int num = Integer.parseInt(qtyMaintainField1.getText()) + 1;
        qtyMaintainField1.setText(num + "");
        qtyMaintainMinus1.setEnabled(true);
    }//GEN-LAST:event_qtyMaintainPlus1MouseClicked

    private void confirm1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirm1MouseClicked
        /*insert item*/
        String[] item = new String[6];
        item[0] = itemNameField1.getText();
        item[1] = itemBrandField1.getText();
        item[2] = categoryField1.getSelectedItem().toString();
        item[3] = qtyRemField1.getText();
        item[4] = qtyMaintainField1.getText();
        item[5] = storeLocField1.getText();


        if (!"".equals(item[0]) && !"".equals(item[1]) && !"".equals(item[2])) {
            f.insertItem(item);
            JOptionPane.showMessageDialog(null, "Item record successfully inserted!");
            refresh();
        } else {
            JOptionPane.showMessageDialog(null, "Please fill in all information");
        }
    }//GEN-LAST:event_confirm1MouseClicked

    private void displayCriticalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayCriticalButtonMouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        String[][] list = f.displayCritical();
        displayTable(list);
    }//GEN-LAST:event_displayCriticalButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public void displayTable(String[][] list) {
        try {
            int x;
            for(x=0; list[x][0]!=null; x++) {

                Object[] row = {x+1, list[x][0], list[x][1], list[x][2], list[x][3], list[x][4], list[x][5]};

                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

                model.addRow(row);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void refresh() {
        /*display table - original form*/
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        String[][] list = f.displayItems();
        displayTable(list);

        /*reset search bar*/
        searchBar.setText("");

        /*reset update tab*/
        qtyRemMinus.setEnabled(false);
        qtyMaintainMinus.setEnabled(false);

        /*reset insert tab*/
        itemBrandField1.setText("");
        itemNameField1.setText("");
        categoryField1.setSelectedIndex(0);
        qtyRemField1.setText("0");
        qtyMaintainField1.setText("0");
        storeLocField1.setText("");
        qtyRemMinus1.setEnabled(false);
        qtyMaintainMinus1.setEnabled(false);
        
        editItemPanel.setVisible(false);
        clickAnItemLabel.setVisible(true);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IS_AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IS_AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IS_AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IS_AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IS_AdminPanel().setVisible(true);;
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InventoryStatus;
    private javax.swing.JComboBox<String> categoryField;
    private javax.swing.JComboBox<String> categoryField1;
    private javax.swing.JLabel clickAnItemLabel;
    private javax.swing.JButton confirm;
    private javax.swing.JButton confirm1;
    private javax.swing.JButton displayCriticalButton;
    private javax.swing.JPanel editItemPanel;
    private javax.swing.JTextField itemBrandField;
    private javax.swing.JTextField itemBrandField1;
    private javax.swing.JTextField itemIdField;
    private javax.swing.JTextField itemNameField;
    private javax.swing.JTextField itemNameField1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField qtyMaintainField;
    private javax.swing.JTextField qtyMaintainField1;
    private javax.swing.JButton qtyMaintainMinus;
    private javax.swing.JButton qtyMaintainMinus1;
    private javax.swing.JButton qtyMaintainPlus;
    private javax.swing.JButton qtyMaintainPlus1;
    private javax.swing.JTextField qtyRemField;
    private javax.swing.JTextField qtyRemField1;
    private javax.swing.JButton qtyRemMinus;
    private javax.swing.JButton qtyRemMinus1;
    private javax.swing.JButton qtyRemPlus;
    private javax.swing.JButton qtyRemPlus1;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField searchBar;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField storeLocField;
    private javax.swing.JTextField storeLocField1;
    // End of variables declaration//GEN-END:variables
}
